### ISSUE TITLE
The meaning is not so clear in these passages

### ISSUE THREAD

**Issue by GeoDoo** [frameworkless-movement/manifesto#24]
1. "They are the most powerful tools to learn how to code without them."
2. "Having clear opportunities and constraints of each framework it will be easier make the right choice, also it will be clear when you don't need a framework"
3. "Frameworkless means, however, don't assume that in the software I'm writing I can afford to delegate this responsibility and depends on other (library for example) to solve a specific problem. Or worse: don't reinvent the wheel and bind hand and foot to a whole framework even if I don't really need"
4. "But it means taking a conscious decision about if we want to get help to do our own job from tools already exist and in what way"

The syntax above does not convey a clear message. I cannot understand exactly what you are saying. 

Lastly, in the section What Frameworkless Movement IS NOT, the last two arguments are about what it DOES mean, so it is kinda confusing too. Maybe they should move to the purpose section??

:)

**Comment by francesco-strazzullo** [comment]
For the first point, you can read the discussion in this closed issue #5.

> "Having clear opportunities and constraints of each framework it will be easier make the right choice, also it will be clear when you don't need a framework"

Apart from the syntax error, "it will be easier **to** make the right choice", I try to explain better what we mean. This phrase is connected to #21, in order to choose a good tool you should understand clearly what opportunities and constraints they have and how well these opportunities are adaptable to your context.

> "Frameworkless means, however, don't assume that in the software I'm writing I can afford to delegate this responsibility and depends on other (library for example) to solve a specific problem. Or worse: don't reinvent the wheel and bind hand and foot to a whole framework even if I don't really need"

The point here is that you should remember that writing a software without a framework it's possible. Sometimes devs use the "usual" framework also if they don't really need that. The focus here is on "delegation". If I decide that I want to delegate the solution of a problem to a framework/library, I sacrifice control because I *depend* on that library. What we are trying to state here is to think about the loss of control when choosing a tool.

> "But it means taking a conscious decision about if we want to get help to do our own job from tools already exist and in what way"

Here what we mean is that we don't say that we need to write without frameworks **every single time** but you should decide in you need help for that project and how to use that tool.

@GeoDoo It's more clear now? How can we write this in a better way?

**Comment by francesco-strazzullo** [comment]
@GeoDoo for the last point you may be right. If you have a better idea I suggest opening a PR to move that paragraphs in the right place.

**Comment by GeoDoo** [comment]
@francesco-strazzullo I will open a PR (as soon I find some free time) with the changes I proposed and we discuss it there. Thanks

**Comment by francesco-strazzullo** [comment]
@GeoDoo any news on this issue?

**Comment by GeoDoo** [comment]
@francesco-strazzullo I am on it! Gimme some time please...

**Comment by GeoDoo** [comment]
@francesco-strazzullo here you are: https://github.com/frameworkless-movement/manifesto/pull/27

**Comment by francesco-strazzullo** [comment]
Fixed by #27
