### ISSUE TITLE
Ui-editor - a tool that generates framework code

### ISSUE THREAD

**Issue by ghost** [frameworkless-movement/manifesto#41]
Hi,

My name is Vetrivel. I am building a concept  tool to build components. The tool generates code for a targeted framework and currently generates code for reactjs.

Saw your post and I though I'll share my work hereas the vision seems to be the same.

Here is the link to my project. https://github.com/imvetri/ui-editor

Here is the video for code generation demo https://vimeo.com/386239546

I recently removed some features from the tool which wasn't needed for the direction I'm going forward. But if you need help / questions / build POCs feel free to let me know.

**Comment by francesco-strazzullo** [comment]
Hi @imvetri, I think that this issue is quite out of the scope here. We use GitHub issues to talk about principles and decisions about frameworks. If you think that your tool is built with the same vision you can add our badge on your project https://github.com/frameworkless-movement/frameworkless-movement.github.io/blob/master/img/frameworkless__badge-github.svg
