### ISSUE TITLE
Frameworks as "tools" to learn

### ISSUE THREAD

**Issue by francesco-strazzullo** [frameworkless-movement/manifesto#5]
this is one the questions created by @apiraino in issue #1.

Quoting @apiraino

> from the manifesto: [frameworks] are the most powerful tool to learn how to code without them not sure about the meaning of this.

**Comment by adellava** [comment]
There are two important concepts inside this phrase:

1. In order to know how and when you should use one particular framework you have to understand how framworks work. Having clear opportunities and constraints of each framework it will be easier make the right choice, also it will be clear when you don't need a framwork.

2. Understanding how frameworks works behind the scenes will improve your awareness about vanilla javascript. Every framework is written in vanilla javascript and is very generic. Knowing the frameworks rationali you will able to write better specific code. For example a rendering algorithm ad hoc for your application without depend from a framework.

**Comment by apiraino** [comment]
That's a crystal clear explaination :+1: thanks!

**Comment by francesco-strazzullo** [comment]
@apiraino we added some information from this issue on the README.MD. You can check the PR #11
